### ISSUE TITLE
Numpy version issues

### ISSUE THREAD

**Issue by ReneHeim** [reflectdetect/reflectdetect#24]
After installing reflect detect on Windows 11, I ran into the following issue when trying to run the geolocation or the apriltag module : 

> A module that was compiled using NumPy 1.x cannot be run in
> NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
> versions of NumPy, modules must be compiled with NumPy 2.0.
> Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
> 
> If you are a user of the module, the easiest solution will be to
> downgrade to 'numpy<2' or try to upgrade the affected module.
> We expect that some modules will need time to support NumPy 2.
> 
> Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\reneh\anaconda3\Scripts\reflectdetect-converter.exe\__main__.py", line 4, in <module>
>     from reflectdetect.raw_to_radiance import main
>   File "C:\Users\reneh\anaconda3\Lib\site-packages\reflectdetect\raw_to_radiance.py", line 4, in <module>
>     from matplotlib import pyplot as plt
>   File "C:\Users\reneh\anaconda3\Lib\site-packages\matplotlib\__init__.py", line 159, in <module>
>     from . import _api, _version, cbook, _docstring, rcsetup
>   File "C:\Users\reneh\anaconda3\Lib\site-packages\matplotlib\rcsetup.py", line 28, in <module>
>     from matplotlib.colors import Colormap, is_color_like
>   File "C:\Users\reneh\anaconda3\Lib\site-packages\matplotlib\colors.py", line 57, in <module>
>     from matplotlib import _api, _cm, cbook, scale
>   File "C:\Users\reneh\anaconda3\Lib\site-packages\matplotlib\scale.py", line 22, in <module>
>     from matplotlib.ticker import (
>   File "C:\Users\reneh\anaconda3\Lib\site-packages\matplotlib\ticker.py", line 144, in <module>
>     from matplotlib import transforms as mtransforms
>   File "C:\Users\reneh\anaconda3\Lib\site-packages\matplotlib\transforms.py", line 49, in <module>
>     from matplotlib._path import (
> Traceback (most recent call last):
>   File "C:\Users\reneh\anaconda3\Lib\site-packages\numpy\core\_multiarray_umath.py", line 44, in __getattr__
>     raise ImportError(msg)
> ImportError:
> A module that was compiled using NumPy 1.x cannot be run in
> NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
> versions of NumPy, modules must be compiled with NumPy 2.0.
> Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
> 
> If you are a user of the module, the easiest solution will be to
> downgrade to 'numpy<2' or try to upgrade the affected module.
> We expect that some modules will need time to support NumPy 2.
> 
> 
> ImportError: numpy.core.multiarray failed to import
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\reneh\anaconda3\Scripts\reflectdetect-converter.exe\__main__.py", line 4, in <module>
>   File "C:\Users\reneh\anaconda3\Lib\site-packages\reflectdetect\raw_to_radiance.py", line 4, in <module>
>     from matplotlib import pyplot as plt
>   File "C:\Users\reneh\anaconda3\Lib\site-packages\matplotlib\__init__.py", line 159, in <module>
>     from . import _api, _version, cbook, _docstring, rcsetup
>   File "C:\Users\reneh\anaconda3\Lib\site-packages\matplotlib\rcsetup.py", line 28, in <module>
>     from matplotlib.colors import Colormap, is_color_like
>   File "C:\Users\reneh\anaconda3\Lib\site-packages\matplotlib\colors.py", line 57, in <module>
>     from matplotlib import _api, _cm, cbook, scale
>   File "C:\Users\reneh\anaconda3\Lib\site-packages\matplotlib\scale.py", line 22, in <module>
>     from matplotlib.ticker import (
>   File "C:\Users\reneh\anaconda3\Lib\site-packages\matplotlib\ticker.py", line 144, in <module>
>     from matplotlib import transforms as mtransforms
>   File "C:\Users\reneh\anaconda3\Lib\site-packages\matplotlib\transforms.py", line 49, in <module>
>     from matplotlib._path import (
> ImportError: initialization failed

How can this be fixed? I am running Numpy 2.13 in my conda environment. 

Thanks, 

Rene

**Comment by ReneHeim** [comment]
ERROR: Cannot install reflectdetect==0.1.0, reflectdetect==0.1.10, reflectdetect==0.1.11, reflectdetect==0.1.12, reflectdetect==0.1.13, reflectdetect==0.1.2, reflectdetect==0.1.3, reflectdetect==0.1.4, reflectdetect==0.1.5, reflectdetect==0.1.6, reflectdetect==0.1.7, reflectdetect==0.1.8, reflectdetect==0.1.9 and reflectdetect==1.0.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    reflectdetect 1.0.0 depends on robotpy-apriltag<2025.0.0.0 and >=2024.3.2.1
    reflectdetect 0.1.13 depends on robotpy-apriltag<2025.0.0.0 and >=2024.3.2.1
    reflectdetect 0.1.12 depends on robotpy-apriltag<2025.0.0.0 and >=2024.3.2.1
    reflectdetect 0.1.11 depends on robotpy-apriltag<2025.0.0.0 and >=2024.3.2.1
    reflectdetect 0.1.10 depends on robotpy-apriltag<2025.0.0.0 and >=2024.3.2.1
    reflectdetect 0.1.9 depends on robotpy-apriltag<2025.0.0.0 and >=2024.3.2.1
    reflectdetect 0.1.8 depends on robotpy-apriltag<2025.0.0.0 and >=2024.3.2.1
    reflectdetect 0.1.7 depends on robotpy-apriltag<2025.0.0.0 and >=2024.3.2.1
    reflectdetect 0.1.6 depends on robotpy-apriltag<2025.0.0.0 and >=2024.3.2.1
    reflectdetect 0.1.5 depends on robotpy-apriltag<2025.0.0.0 and >=2024.3.2.1
    reflectdetect 0.1.4 depends on robotpy-apriltag<2025.0.0.0 and >=2024.3.2.1
    reflectdetect 0.1.3 depends on robotpy-apriltag<2025.0.0.0 and >=2024.3.2.1
    reflectdetect 0.1.2 depends on robotpy-apriltag<2025.0.0.0 and >=2024.3.2.1
    reflectdetect 0.1.0 depends on robotpy-apriltag<2025.0.0.0 and >=2024.3.2.1

**Comment by Tingel24** [comment]
This issue was caused by a `poetry.lock` file that had been mistakenly checked in. After removing the file and lifting the strict version requirements the issue should be fixed now.
